[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "buptmw"
dynamic = ["version"]
authors = [
    {name = "ZeroCore", email = "esetting@hotmail.com"}
]
description = "Help BUPT students access school system with python."
keywords = ["BUPT"]
readme = "README.md"
license = "GPL-3.0-or-later"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython"
]

requires-python = ">= 3.11"
dependencies = [
    "requests>=2.32.5",
    "beautifulsoup4>=4.13.5",
    "lxml>=6.0.2",
    "ddddocr>=1.5.6",
]

[dependency-groups]
dev = [
    "hatch>=1.17.0",
]

[project.urls]
Homepage = "https://github.com/ZeroCore-Zero/BUPT_Middleware"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/LICENSE",
    "/README.md",
]
